CREATE TABLE CHAMPIONS (
		ID INTEGER,
		TITLE VARCHAR(255),
		NAME VARCHAR(255),
		CHAMPKEY VARCHAR(255)
	);
CREATE TABLE SUMMONERSPELLS (
		ID INTEGER,
		NAME VARCHAR(255),
		SPELLKEY VARCHAR(255)
);

CREATE TABLE APP.MATCHMAKINGQUEUE (
	ID INTEGER PRIMARY KEY,
	MAP VARCHAR(255),
	DESCRIPTION VARCHAR(255) NULL
);


INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (0, 'Custom Game', NULL);
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (72, 'Howling Abyss', '1v1 Snowdown Showdown games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (73, 'Howling Abyss', '2v2 Snowdown Showdown games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (75, 'Summoner''s Rift', '6v6 Hexakill games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (76, 'Summoner''s Rift', 'Ultra Rapid Fire games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (78, 'Howling Abyss', 'One For All: Mirror Mode games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (83, 'Summoner''s Rift', 'Co-op vs AI Ultra Rapid Fire games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (98, 'Twisted Treeline', '6v6 Hexakill games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (100, 'Butcher''s Bridge', '5v5 ARAM games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (310, 'Summoner''s Rift', 'Nemesis games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (313, 'Summoner''s Rift', 'Black Market Brawlers games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (317, 'Crystal Scar', 'Definitely Not Dominion games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (325, 'Summoner''s Rift', 'All Random games');

INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (400, 'Summoner''s Rift', '5v5 Draft Pick games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (420, 'Summoner''s Rift', '5v5 Ranked Solo games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (430, 'Summoner''s Rift', '5v5 Blind Pick games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (440, 'Summoner''s Rift', '5v5 Ranked Flex games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (450, 'Howling Abyss', '5v5 ARAM games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (460, 'Twisted Treeline', '3v3 Blind Pick games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (470, 'Twisted Treeline', '3v3 Ranked Flex games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (600, 'Summoner''s Rift', 'Blood Hunt Assassin games');

INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (610, 'Cosmic Ruins', 'Dark Star: Singularity games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (700, 'Summoner''s Rift', 'Clash games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (800, 'Twisted Treeline', 'Co-op vs. AI Intermediate Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (810, 'Twisted Treeline', 'Co-op vs. AI Intro Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (820, 'Twisted Treeline', 'Co-op vs. AI Beginner Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (830, 'Summoner''s Rift', 'Co-op vs. AI Intro Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (840, 'Summoner''s Rift', 'Co-op vs. AI Beginner Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (850, 'Summoner''s Rift', 'Co-op vs. AI Intermediate Bot games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (900, 'Summoner''s Rift', 'ARURF games');

INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (910, 'Crystal Scar', 'Ascension games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (920, 'Howling Abyss', 'Legend of the Poro King games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (940, 'Summoner''s Rift', 'Nexus Siege games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (950, 'Summoner''s Rift', 'Doom Bots Voting games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (960, 'Summoner''s Rift', 'Doom Bots Standard games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (980, 'Valoran City Park', 'Star Guardian Invasion: Normal games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (990, 'Valoran City Park', 'Star Guardian Invasion: Onslaught games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (1000, 'Overcharge', 'PROJECT: Hunters games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (1010, 'Summoner''s Rift', 'Snow ARURF games');
INSERT INTO APP.MATCHMAKINGQUEUE(ID, MAP, DESCRIPTION) VALUES (1020, 'Summoner''s Rift', 'One for All games');

